/*
 * halComparator.c
 */	

#include "halComparator.h"
#include "SI_EFM8SB2_Register_Enums.h"

void halComparator1_Init (void)
{
    unsigned char delay;
    
    // $[CMP0MX - Comparator 0 Multiplexer Selection]
    /*
     // CMXP (Comparator Positive Input MUX Selection) = CMP0P4 (External pin
     //     CMP0P.4.)
     // CMXN (Comparator Negative Input MUX Selection) = VDD_DIV_2 (VDD
     //     divided by 2.)
     */
    CMP1MX = CMP1MX_CMXP__VDD_DIV_2 | CMP1MX_CMXN__CMP1N0;

    // Delay to allow the comparator inputs to settle
    for (delay = 0; delay < 0x20; delay++);
    // [CMP0MX - Comparator 0 Multiplexer Selection]$
    
    // $[CMP0MD - Comparator 0 Mode]
    /*
     // CPMD (Comparator Mode Select) = MODE3 (Mode 3 (Slowest Response Time,
	 //     Lowest Power Consumption))
     // CPFIE (Comparator Falling-Edge Interrupt Enable) = FALL_INT_ENABLED
     //     (Comparator falling-edge interrupt enabled.)
     */
    CMP1MD &= ~CMP1MD_CPMD__FMASK;
    // [CMP0MD - Comparator 0 Mode]$
    
    CMP1CN0 &= ~(CMP1CN0_CPFIF__FALLING_EDGE | CMP1CN0_CPRIF__RISING_EDGE);

    CMP1CN0 |= CMP1CN0_CPEN__ENABLED;

    IE |= IE_EA__ENABLED;
    EIE1 |= EIE1_ECP1__ENABLED;

    // ECP0 (Comparator0 (CP0) Interrupt Enable) = ENABLED (Enable interrupt
    //     requests generated by the comparator 0 CPRIF or CPFIF flags.)
}


void halComparator1_Deinit (void)
{
	CMP1CN0 &= ~CMP1CN0_CPEN__ENABLED;

	CMP1CN0 &= ~(CMP1CN0_CPFIF__FALLING_EDGE | CMP1CN0_CPRIF__RISING_EDGE);

    CMP1MD &= ~CMP1MD_CPFIE__FALL_INT_ENABLED;
}




