//=========================================================
// src/Interrupts.c: generated by Hardware Configurator
//
// This file will be regenerated when saving a document.
// leave the sections inside the "$[...]" comment tags alone
// or they will be overwritten!
//=========================================================

// USER INCLUDES
#include <SI_EFM8SB2_Register_Enums.h>
#include "../4_Source/0_BL/blStatusControl/blStatusControl.h"


#define SAMPLING_NUMBER            1//256 // Number of samples per calculation

unsigned long ADC_SAMPLES;               // Accumulates the ADC samples
unsigned char ADC_CONV_COMPLETE;              // ADC accumulated result ready flag


//-----------------------------------------------------------------------------
// ADC0EOC_ISR
//-----------------------------------------------------------------------------
//
// ADC0EOC ISR Content goes here. Remember to clear flag bits:
// ADC0CN0::ADINT (Conversion Complete Interrupt Flag)
//
//-----------------------------------------------------------------------------
SI_INTERRUPT (ADC0EOC_ISR, ADC0EOC_IRQn)
{
	ADC0CN0_ADINT = 0;// Clear ADC0 conv. complete flag

	ADC_SAMPLES = ADC0 >> 6;
	ADC_CONV_COMPLETE = 0;// Set result ready flag

	blStatusControl_SetConvCompleteFlag(ADC_CONV_COMPLETE);

	blStatusControl_SetADC_ConvValue(ADC_SAMPLES);
}

//-----------------------------------------------------------------------------
// RTC0FAIL_ISR
//-----------------------------------------------------------------------------
//
// RTC0FAIL ISR Content goes here. Remember to clear flag bits:
// RTC0CN0::OSCFAIL (RTC Oscillator Fail Event Flag)
//
//-----------------------------------------------------------------------------
SI_INTERRUPT (RTC0FAIL_ISR, RTC0FAIL_IRQn)
{

}



